version: '3.1'

services:

  mongo:
    container_name: mongodb
    image: mongo:4.4.22
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1
      MONGO_INITDB_DATABASE: database1
    volumes:
      - data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  adminmongo:
    container_name: adminmongo
    image: mrvautin/adminmongo:latest
    restart: always
    ports:
      - 1234:1234
    environment: 
      HOST: 0.0.0.0
      CONN_NAME: admin_conn
      DB_USERNAME: root
      DB_PASSWORD: root1
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: database1
    links:
      - mongo
volumes:
  data: 